#ifndef __MACRO_H__
#define __MACRO_H__

#define COMMONASSET "ACT"

#define WALLET_WIDTH 960
#define WALLET_HEIGHT 580

#define AUTO_REFRESH_TIME 30000
#define PWD_LOCK_TIME 7200
#define ACHAIN_ACCOUNT_MAX 50

#define VERSION_CONFIG "version.ini"
#define UPDATE_TOOL_NAME "AchainUp.exe"

#ifdef WIN32
#define ACHAIN_WALLET_VERSION "2.0.1"
#else
#define ACHAIN_WALLET_VERSION "2.0.1"
#endif
#define ACHAIN_WALLET_VERSION_STR "v" ACHAIN_WALLET_VERSION

#define TEST_CHAIN

#ifdef TEST_CHAIN
#define ACHAIN_BROWSER_URL ""
#define BROWSER_SERVER_DOMAIN ""
#define WALLET_SERVER_DOMAIN ""
#else
#define ACHAIN_BROWSER_URL ""
#define BROWSER_SERVER_DOMAIN ""
#define WALLET_SERVER_DOMAIN ""
#endif

#define REPORT_REQ BROWSER_SERVER_DOMAIN ""
#define BALANCE_REQ BROWSER_SERVER_DOMAIN ""
#define TRANSACTION_REQ BROWSER_SERVER_DOMAIN ""
#define OTHER_TOKEN_REQ BROWSER_SERVER_DOMAIN ""
#define CON_CONFOG_URL BROWSER_SERVER_DOMAIN ""
#define BROADCAST_URL BROWSER_SERVER_DOMAIN ""
#define QUOTATION_URL WALLET_SERVER_DOMAIN ""
#define EXCHANGE_RATE_URL WALLET_SERVER_DOMAIN ""
#define TRACK_URL WALLET_SERVER_DOMAIN ""

#endif // __MACRO_H__
